// <auto-generated />
namespace GVSU.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05));
        
        string IMigrationMetadata.Id
        {
            get { return "201604130447470_05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
